name: Disaster Recovery Drill

on:
  schedule:
    # Run monthly on the first Monday at 2 AM UTC
    - cron: '0 2 1-7 * 1'
  workflow_dispatch:
    inputs:
      shadow_project_ref:
        description: 'Shadow project reference (optional)'
        required: false
        type: string
      restore_time:
        description: 'Restore time (ISO format, optional)'
        required: false
        type: string

env:
  PRISMA_CLIENT_ENGINE_TYPE: wasm

jobs:
  dr-drill:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install ts-node
      run: npm install -g ts-node

    - name: Run DR Drill
      run: |
        npx ts-node scripts/clone-and-restore-check.ts
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        SHADOW_PROJECT_REF: ${{ github.event.inputs.shadow_project_ref }}

    - name: Upload DR Report
      uses: actions/upload-artifact@v4
      with:
        name: dr-report
        path: reports/dr/
        retention-days: 90

    - name: Comment on PR (if triggered by PR)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🔄 **DR Drill Completed**: Check the artifacts for the disaster recovery report.'
          })

    - name: Create Issue on Failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🚨 DR Drill Failed - Immediate Attention Required',
            body: `The monthly DR drill failed. Please investigate immediately.
            
            **Workflow**: ${context.workflow}
            **Run ID**: ${context.runId}
            **Commit**: ${context.sha}
            
            Check the workflow logs for details.`,
            labels: ['urgent', 'dr', 'incident']
          })
